"""Initial tables

Revision ID: 85d9ed6b0712
Revises: 
Create Date: 2026-01-07 11:11:04.737871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85d9ed6b0712'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'EUR', 'GBP', 'CHF', name='currency', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('name', name=op.f('uq_accounts_name'))
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('original_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('original_currency', sa.Enum('USD', 'EUR', 'GBP', 'CHF', name='currency', native_enum=False), nullable=False),
    sa.Column('value_in_account_currency', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('date_str', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_transactions_account_id_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('accounts')
    # ### end Alembic commands ###
